Implement/consensus/rpc #16
BlocSoc-iitr/selene pull request #21
Opened 2024-08-28 12:42 UTC by x-senpai-x

Implemented consensus_rpc.go, nimbus_rpc.go,mock_rpc.go .In mock_rpc.go used the testdata of helios  and added it here in testdata folder , made a folder consensus/consensus_core to define the structs

2024-08-28 12:53 UTC, x-senpai-x commented
@star-gazer111  please review this

2024-08-29 16:41 UTC, gerceboss commented on consensus/consensus_core/consensus_core.go
> +	randao_reveal            SignatureBytes
correct the spelling mistakes please, check at other places as well

2024-08-29 23:21 UTC, gerceboss commented on consensus/consensus_core/consensus_core.go
> +	randao_reveal            SignatureBytes
Add unit tests as well for some functions that use concurrency

2024-08-30 08:44 UTC, gerceboss commented
I think we need to split this PR in two parts, one which adds data(json) and other adding the code logic. What's your take on this ? @star-gazer111

2024-08-30 19:33 UTC, x-senpai-x commented on consensus/consensus_core/consensus_core.go
> +	randao_reveal            SignatureBytes
> correct the spelling mistakes please, check at other places as well

@gerceboss Sir which spelling mistakes ? ig the only spelling mistakes I have made are in comments that I have added other than that for naming conventions at most places I have copied the names from helios

2024-08-31 10:10 UTC, star-gazer111 commented
> I think we need to split this PR in two parts, one which adds data(json) and other adding the code logic. What's your take on this ? @star-gazer111

I think we can go ahead with this only for now.

2024-08-31 10:14 UTC, star-gazer111 requested changes

2024-08-31 10:14 UTC, star-gazer111 commented on common/types.go
>  }
What did you change here?

2024-08-31 10:14 UTC, star-gazer111 commented on common/types.go
and here?

2024-08-31 10:14 UTC, star-gazer111 commented on common/types.go
> +	return fmt.Sprintf("%d", b.Number)
here also?

2024-08-31 10:14 UTC, star-gazer111 commented on common/types.go
> +		}
these extra whitespaces are for?

2024-08-31 10:14 UTC, star-gazer111 commented on consensus/rpc/nimbus_rpc.go
> +)
are these values taken from helios ? @x-senpai-x

2024-08-31 10:43 UTC, x-senpai-x commented on common/types.go
>  }
> What did you change here?
Before issuing the first pr i didn't use gofmt 
So I ran it before issuing the second pr 
But There have been no changes in this file

2024-08-31 10:44 UTC, x-senpai-x commented on common/types.go
> +		}
In common/types.go whitespaces were introduced after running gofmt

2024-08-31 10:47 UTC, x-senpai-x commented on consensus/rpc/nimbus_rpc.go
> +)
in helios they used default settings of backoffsettings package which had  the same values

2024-08-31 10:52 UTC, star-gazer111 approved these changes
LGTM.

2024-08-31 10:53 UTC, star-gazer111 commented on consensus/consensus_core/consensus_core.go
> +	randao_reveal            SignatureBytes
We can mereg this once @gerceboss approves at his end as well.

2024-08-31 13:16 UTC, gerceboss commented
LGTM as well, merging the  @x-senpai-x , just mention while making the PR if you are adding any constant values referencing to helios

2024-08-31 13:17 UTC, merged