Created utils.go
BlocSoc-iitr/selene pull request #41
Opened 2024-09-20 01:09 UTC by DarkLord017

Please check all the functions

2024-09-20 02:29 UTC, DarkLord017 commented
Implemented consensus/utils.go & corrected consensus/rpc & consensus/consensus_core.go

Please check the functions in utils.go 
@star-gazer111

2024-09-20 07:42 UTC, DarkLord017 commented
@star-gazer111 sir consensus_core me kuch chize implemented nahi hai to usme changes me kru ya @0xpseudo kre ?
utsav ne bas us vakt jo kaam aa rha tha vahi implement kiya tha
PR abhi vapis draft krdi hai

2024-09-20 09:27 UTC, star-gazer111 requested changes

2024-09-20 09:27 UTC, star-gazer111 commented on consensus/utils.go
> +
this stuff is already implemented [here](https://github.com/BlocSoc-iitr/selene/blob/dev/config/types.go). Why are you reimplementing the same stuff?

2024-09-20 12:02 UTC, DarkLord017 commented on consensus/utils.go
> +
Ok sir I'll correct it

2024-09-21 11:22 UTC, DarkLord017 commented
Please refer to PR #51

2024-09-27 19:44 UTC, star-gazer111 commented
@DarkLord017 this PR is for?

2024-09-27 19:53 UTC, DarkLord017 commented
It is already merged (it was for consensus/utils.go) refer #51

2024-09-27 19:54 UTC, closed without merging